name: publish my library

env:
 CI: true

on:
 push:
   branches:
     - main
   tags:
     - "!*"

jobs:
 publish:
   name: Setup
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v2
    
     # Nodeのバージョンを指定
     - name: setup node
       uses: actions/setup-node@v1
       with:
         node-version: 18.12
         registry-url: https://npm.pkg.github.com

     # 必要なモジュール（typescript）をインストール
     - name: install node_modules
       run: npm install

     # パッケージとして公開する
     - name: publish
       run: npx can-npm-publish --verbose && npm publish || echo "No need to publish"
       env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
